### ISSUE TITLE
Building issues Win64

### ISSUE THREAD

**Issue by meaningofshape** [stevengj/Blosc.jl#10]
I am having trouble  adding package Blosc.jl on my 64bit Window7 system.  Once the process gets to INFO: Building Blosc, nothing seems to happen except the spinning indicator.  This used to work fine. I have recently reinstalled Julia and need to add back some of the packages.  I don't know if I have made other changes that could have impacted this package.  I ran across this problem trying to use MAT.jl.  Can you provide some advice on how to proceed?
Thank you.

**Comment by stevengj** [comment]
Maybe your machine is having trouble downloading because of some firewall thing?

What happens if you just type `download("http://ab-initio.mit.edu/blosc/libblosc64-1.5.3.dll")` in Julia?

See also timholy/HDF5.jl#234

**Comment by meaningofshape** [comment]
I suspended my virus protection and was able to successfully add the Blosc.jl package. Also, the above download("http://..) command did run and returned a path in my REPL C:\\...\\julFCDB.tmp.  I still cannot 'build' the Blosc.jl package.  It spins out when trying Pkg.build("Blosc") and as part of the Pkg.build("HDF5") process- which I am still asked to do when trying 'using MAT'.  

I did see the timholy/HDF5.jl#234 issue and it could be related.  I just don't really know what they are talking about.  curl? CA bundle?  I don't know how to implement their suggestions.

**Comment by tkelman** [comment]
Can you watch in task manager and see what external programs are running, how their cpu and memory consumption are behaving? In Julia, what does the following return?
```
using BinDeps
using Compat
vers = "1.5.3";
target = "libblosc.$(Libdl.dlext)";
download_cmd("http://ab-initio.mit.edu/blosc/libblosc$WORD_SIZE-$vers.dll", target)
```

**Comment by meaningofshape** [comment]
@tkelman the above code results in: 'powershell -Command'(new-object net.webclient). DownloadFile("http://ab-initio.mit.edu/blosc/libblosc64-1.5.3.dll", "libblosc.dll")'

I don't see any unusual processes running.  However, I am now getting a new message in Julia when I Pkg.build("Blosc"), while the indicator continues to spin:

INFO: Building Blosc
Exception calling "DownloadFile" with "2" argument(s): "Unable to connect to th
e remote server"
At line:1 char:40
+ (new-object net.webclient).DownloadFile <<<< ("http://ab-initio.mit.edu/blosc
/libblosc64-1.5.0.dll", "libblosc.dll")
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DotNetMethodException

**Comment by stevengj** [comment]
Does that download link work for you in the browser?

I wonder if I should just put the binaries on github (in a branch of the `Blosc.jl` repository), if my group webserver (ab-initio.mit.edu) is dislike by corporate firewalls or something.

Or someone could set up the whole WinRPM + Homebrew thing, although that seems like an overly complex solution to just posting a `.dll` and `.dylib` file.

**Comment by meaningofshape** [comment]
The download link does work in my browser.  I am not behind a corporate firewall- just at home.

**Comment by meaningofshape** [comment]
It could still be my Kaspersky Antivirus?  I have disabled everything I can find, but I still see avp.exe*32 running and it takes up more memory when I Pkg.build("Blosc").  I am trying to figure out how to completely shut this down.

**Comment by tkelman** [comment]
@stevengj another option is bintray, I moved a bunch of things there recently. Their web UI takes a few more clicks than I'd like to upload things manually, but it seems to work and is https.

**Comment by meaningofshape** [comment]
Thanks for your help on this.  I have not been able to solve this problem, so I am going to uninstall this package and others that use it (MAT, HDF5) and find alternative ways to manage data.

**Comment by tkelman** [comment]
I believe Blosc is an optional dependency for MAT and HDF5, and they should still be able to work without it. @stevengj I made a julialang organization on bintray if you'd like to try hosting files there, see if it works any better. Using github releases may also work.

**Comment by stevengj** [comment]
@tkelman, bintray sounds fine to me.  How do I use the julialang org there?

**Comment by tkelman** [comment]
There should be a "Join" button at https://bintray.com/julialang

The process of creating and uploading a new package is a bunch of steps through their UI, or you can script via curl. Through the UI the sequence is:

1. Go to https://bintray.com/julialang/generic, click "Add New Package"
2. Fill in at least Name, License, and Version control (a link I assume), check "Make download numbers in stats public" if you want, click Create Package
3. Click Versions List
4. Click Create new version
5. Fill in version name, click Create Version
6. At the top where it says "julialang/generic/name/#.#.#", click the version number
7. Click Files
8. Click "via the UI"
9. On the bottom right hit "Click to Add Files..." to upload
10. Click Save Changes
11. Click Publish in the message "Notice: You have 1 unpublished item(s) for this version (expiring in 6 days and 22 hours) Discard | Publish" that comes up

A few too many steps, but oh well. File should then be available at https://bintray.com/artifact/download/julialang/generic/foo

**Comment by meaningofshape** [comment]
It is not easy to find a replacement for MAT.jl-- all of my work is in MATLAB and much of my community uses MATLAB. This did  work at one point and was very enjoyable to use. 

I would appreciate any help you could offer to get Blosc to build on my system.

**Comment by meaningofshape** [comment]
Hi @tkelman  and @stevengj , 
Could we re-open this?  There is no other way for me to manage data that is nearly as convenient as MAT.jl/ HDF5, and I can't use them because I still can't build Blosc.jl.  I would really appreciate your help.
Thanks

**Comment by tkelman** [comment]
What does `Pkg.installed("Blosc")` say? Have you re-tried `Pkg.build("Blosc")` with the latest version 0.1.4?

**Comment by meaningofshape** [comment]
Pkg.installed("Blosc") returns v"0.1.4"Pkg.build("Blosc") results in a spinning icon that never finishesBy the way, I did turn off my Kaspersky antivirus and restart my computer.  It looks to me like all of my anti-virus is off. 


     On Thursday, August 20, 2015 5:55 PM, Tony Kelman <notifications@github.com> wrote:
   

 What does Pkg.installed("Blosc") say? Have you re-tried Pkg.build("Blosc") with the latest version 0.1.4?—

**Comment by tkelman** [comment]
Do you get any output at all?

**Comment by meaningofshape** [comment]
I don't get any output.  Maybe I can try this outside of Juno and see what happens. 


     On Friday, August 21, 2015 9:35 AM, Tony Kelman <notifications@github.com> wrote:
   

 Do you get any output at all?—

**Comment by meaningofshape** [comment]
The same thing happens when using Atom.  There may be some other type of Julia command line repl?  I don't know. 


     On Friday, August 21, 2015 9:38 AM, Wade Henning <wadehenning@yahoo.com> wrote:
   

 I don't get any output.  Maybe I can try this outside of Juno and see what happens. 


     On Friday, August 21, 2015 9:35 AM, Tony Kelman <notifications@github.com> wrote:
   

 Do you get any output at all?—

**Comment by stevengj** [comment]
@meaningofshape, just double-click the Julia program and you will get a command-line interface.

**Comment by meaningofshape** [comment]
Thanks @stevengj .  Blosc does build in the command-line!  I wonder why not in Juno or Atom? 

I still have trouble with 'using MAT', but but I imagine I have to start separate issue for this.  I get 'Error: HDF5File not defined'.  (By the way, what is the Markdown syntax you are using for formatting code and output?
Thanks!

**Comment by stevengj** [comment]
Probably report the bug to Juno; I don't know what is different about that environment.

**Comment by stevengj** [comment]
See https://help.github.com/articles/markdown-basics/#code-formatting on Markdown code formatting.

**Comment by meaningofshape** [comment]
@stevengj, now everything works, even in Juno.  Thanks so much for your help.  I guess just getting the build to go in the command line did the trick?

**Comment by stevengj** [comment]
@meaningofshape, if `Pkg.build` works on the command line but not in Juno, that is a bug with Juno.

**Comment by meaningofshape** [comment]
@stevengj  I totally agree- clearly a bug with Juno.  My point that after going through the command line exercise, it also now builds in Juno.  'using MAT' now works;  all is right in the world!  Thank you for your attention.  I will remember this process as I encounter similar situations in the future and I will bring this to the attention of the Juno team.
