### ISSUE TITLE
can't install Blosc under julia 0.4.6, linux 64-bit Centos 6.8

### ISSUE THREAD

**Issue by StephenVavasis** [stevengj/Blosc.jl#24]
I'm trying to port some of my Julia work from Windows to a Linux server, but I was not able to install the JLD package.  Apparently the problem with JLD is that the Blosc library can't be installed.  Here is the trace.

Thanks,
Steve Vavasis

@cpu135[92]% uname -a
Linux cpu135 2.6.32-642.4.2.el6.x86_64 #1 SMP Tue Aug 23 19:58:13 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
@cpu135[93]% cat /etc/issue
CentOS release 6.8 (Final)
Kernel \r on an \m
@cpu135[97]% ./julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.6 (2016-06-19 17:16 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-unknown-linux-gnu

julia> Pkg.add("Blosc")
INFO: Installing Blosc v0.1.7
INFO: Building Blosc

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
================================[ ERROR: Blosc ]================================

LoadError: failed process: Process(`tar xzf c-blosc-1.8.1.tar.gz --directory=.`, ProcessExited(2)) [2]
while loading /u4/vavasis/.julia/v0.4/Blosc/deps/build.jl, in expression starting on line 20

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: Blosc had build errors.

 - packages with build errors remain installed in /u4/vavasis/.julia/v0.4
 - build the package(s) and all dependencies with `Pkg.build("Blosc")`
 - build a single package by running its `deps/build.jl` script

================================================================================
INFO: Package database updated

julia>

**Comment by stevengj** [comment]
Network glitch?  Try deleting any `v1.8.1.tar.gz` from `~/.julia/v0.4/Blosc/deps` and try again with `Pkg.build("Blosc")`

**Comment by StephenVavasis** [comment]
Steven,
I got an error message from this too.  "Unsupported scheme"?

-- Steve

julia> Pkg.build("Blosc")
INFO: Building Blosc
https://github.com/Blosc/c-blosc/archive/v1.8.1.tar.gz: Unsupported scheme.
================================[ ERROR: Blosc ]================================

LoadError: failed process: Process(`wget -O c-blosc-1.8.1.tar.gz https://github.com/Blosc/c-blosc/archive/v1.8.1.tar.gz`, ProcessExited(1)) [1]
while loading /u4/vavasis/.julia/v0.4/Blosc/deps/build.jl, in expression starting on line 18

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: Blosc had build errors.

 - packages with build errors remain installed in /u4/vavasis/.julia/v0.4
 - build the package(s) and all dependencies with `Pkg.build("Blosc")`
 - build a single package by running its `deps/build.jl` script

================================================================================

**Comment by StephenVavasis** [comment]
Steven,

It appears that 'wget' is somehow not configured correctly on my linux system, so before you bother too much with this, let me ask my sysadmin.

-- Steve

**Comment by stevengj** [comment]
Yeah, if `wget` fails, nothing will work.  (What happens if you type `wget -O c-blosc-1.8.1.tar.gz https://github.com/Blosc/c-blosc/archive/v1.8.1.tar.gz` at the bash prompt?) You might file a bindeps issue about printing a more informative error message once you figure out the problem.
