### ISSUE TITLE
Is the list available compressors mentioned in the README still true?

### ISSUE THREAD

**Issue by xiaodaigh** [stevengj/Blosc.jl#64]
The README states 

> Currently, only the blosclz, lz4, and lz4hc algorithms are included

But `Blosc.compressors()` return 

```
6-element Array{SubString{String},1}:
 "blosclz"
 "lz4"
 "lz4hc"
 "snappy"
 "zlib"
 "zstd"
```

**Comment by stevengj** [comment]
Yes, this should be updated; we added more compressors a while back.
