### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by giordano** [stevengj/Blosc.jl#74]
It would be nice to have a new release, featuring #71.

**Comment by giordano** [comment]
@stevengj Sorry for bumping this so quickly, but installation failures of Blosc are pretty common, #71 should hopefully alleviate them.

**Comment by HarrisonWilde** [comment]
Hi, I am facing a similar issue and can't currently get JLD / Blosc / HDF5 working in current versions

**Comment by stevengj** [comment]
Closed by https://github.com/JuliaRegistries/General/pull/14212

**Comment by giordano** [comment]
Awesome, thank you so much!
