### ISSUE TITLE
update to blosc 1.5.3

### ISSUE THREAD

**Issue by stevengj** [stevengj/Blosc.jl#8]
We are currently using 1.5.0, but upstream has had several updates.

Note that the release notes include updates to the blosc HDF5 plugin, so the corresponding changes should be made to HDF5.jl (updating timholy/HDF5.jl#174).

**Comment by jakebolewski** [comment]
The relevant changes seem to be .

* Explicitly call blosc_init() in HDF5 blosc_filter.c, fixing a segfault.
* Using blosc_compress_ctx() / blosc_decompress_ctx() inside the HDF5 compressor for allowing operation in multiprocess scenarios.
* Reinitializing Blosc during a call to set_nthreads() so as to fix problems with contexts. 

Are any of these user facing or does the C -> Julia translation for the HDF5 plugin need to be updated?

**Comment by stevengj** [comment]
More precisely, the diff is:
```
--- c-blosc-1.5.0/hdf5/blosc_filter.c	2014-11-07 14:01:25.000000000 -0500
+++ c-blosc-1.5.3/hdf5/blosc_filter.c	2015-03-28 06:35:41.000000000 -0400
@@ -105,7 +105,7 @@
     size_t nelements = 8;
     unsigned int values[] = {0,0,0,0,0,0,0,0};
     hid_t super_type;
-    H5T_class_t class;
+    H5T_class_t classt;
 
     r = GET_FILTER(dcpl, FILTER_BLOSC, &flags, &nelements, values, 0, NULL);
     if(r<0) return -1;
@@ -126,8 +126,8 @@
     typesize = H5Tget_size(type);
     if (typesize==0) return -1;
     /* Get the size of the base type, even for ARRAY types */
-    class = H5Tget_class(type);
-    if (class == H5T_ARRAY) {
+    classt = H5Tget_class(type);
+    if (classt == H5T_ARRAY) {
       /* Get the array base component */
       super_type = H5Tget_super(type);
       basetypesize = H5Tget_size(super_type);
@@ -175,7 +175,7 @@
     int doshuffle = 1;             /* Shuffle default */
     int compcode;                  /* Blosc compressor */
     int code;
-    char *compname = NULL;
+    char *compname = "blosclz";    /* The compressor by default */
     char *complist;
     char errmsg[256];
 
@@ -226,12 +226,8 @@
             goto failed;
         }
 
-	/* Select the correct compressor to use */
-        if (compname != NULL)
-	  blosc_set_compressor(compname);
-
-        status = blosc_compress(clevel, doshuffle, typesize, nbytes,
-                                *buf, outbuf, nbytes);
+        status = blosc_compress_ctx(clevel, doshuffle, typesize, nbytes,
+                                    *buf, outbuf, nbytes, compname, 0, 1);
         if (status < 0) {
           PUSH_ERR("blosc_filter", H5E_CALLBACK, "Blosc compression error");
           goto failed;
@@ -264,7 +260,7 @@
           goto failed;
         }
 
-        status = blosc_decompress(*buf, outbuf, outbuf_size);
+        status = blosc_decompress_ctx(*buf, outbuf, outbuf_size, 1);
 
         if(status <= 0){    /* decompression failed */
           PUSH_ERR("blosc_filter", H5E_CALLBACK, "Blosc decompression error");
```

**Comment by stevengj** [comment]
Looks like none of the changes to the HDF5 filter affect us.  The `blosc_compress_ctx` seems to be only for a multi-threaded situation (not multi-process), which doesn't affect us.  The C++ fixes are irrelevant.  I don't see where they added a `blosc_init`, but it doesn't matter because `import Blosc` does that already.

**Comment by stevengj** [comment]
The fact that `blosc_set_nthreads` re-initializes Blosc doesn't really seem to be user-facing either.  (Things like `set_blocksize` and `set_compressor` modify global variables that will persist even after Blosc is re-initialized...the re-initialization just seems to tear down and restart the thread pool.)

**Comment by stevengj** [comment]
Appveyor is failing one of its tests, but it seems to be a network problem (it is freezing on `git clone -q --branch=master git://github.com/stevengj/Blosc.jl.git C:\projects\blosc-jl`)
